apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: job-tracker
  description: A github repo for a service that exposes a dedicated API for jobs and tasks states tracking
  annotations:
    github.com/project-slug: MapColonies/job-tracker
  tags:
    - nodejs
    - typescript
    - expressjs
spec:
  type: service
  lifecycle: production
  owner: Raster
