openapi: 3.0.1
info:
  title: job-tracker
  description: A service that exposes a dedicated API for jobs and tasks states tracking
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /jobs/{jobId}/{taskId}/notify:
    parameters:
      - $ref: '#/components/parameters/jobId'
      - $ref: '#/components/parameters/taskId'
    post:
      operationId: notifyJobFinished
      tags:
        - jobs
      summary: notify tracker on job completion
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/defaultOkMessage'
        404:
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  parameters:
    jobId:
      in: path
      name: jobId
      description: ID of job
      required: true
      schema:
        $ref: '#/components/schemas/jobId'
    taskId:
      in: path
      name: taskId
      description: ID of task
      required: true
      schema:
        $ref: '#/components/schemas/taskId'
  schemas:
    jobId:
      type: string
      format: uuid
    taskId:
      type: string
      format: uuid
    defaultOkMessage:
      type: object
      properties:
        code:
          type: string
          enum:
            - POLYGON_PARTS_TASK_CREATED_SUCCESSFULLY
            - FINALIZATION_TASK_CREATED_SUCCESSFULLY
            - JOB_PROGRESSION_UPDATED_SUCCESSFULLY
            - SET_JOB_STATUS_TO_FAILED
          example: POLYGON_PARTS_TASK_CREATED_SUCCESSFULLY
      required:
        - code
    error:
      type: object
      properties:
        message:
          type: string
        stacktrace:
          type: string
      required:
        - message
