openapi: 3.0.1
info:
  title: job-tracker
  description: A service that exposes a dedicated API for jobs and tasks states tracking
  version: 3.2.2
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /tasks/{taskId}/notify:
    parameters:
      - $ref: '#/components/parameters/taskId'
    post:
      operationId: handleTaskNotification
      tags:
        - tasks
      summary: notify tracker on task finished
      responses:
        '200':
          description: OK
        '400':
          description: Bad task id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '428':
          description: Task neither in "Completed" nor "Failed" status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  parameters:
    taskId:
      in: path
      name: taskId
      description: ID of task
      required: true
      schema:
        $ref: '#/components/schemas/taskId'
  schemas:
    taskId:
      type: string
      format: uuid
    error:
      type: object
      properties:
        message:
          type: string
        stacktrace:
          type: string
      required:
        - message
