openapi: 3.0.1
info:
  title: job-tracker
  description: A service that exposes a dedicated API for jobs and tasks states tracking
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /tasks/{taskId}/notify:
    parameters:
      - $ref: '#/components/parameters/taskId'
    post:
      operationId: notifyTaskFinished
      tags:
        - tasks
      summary: notify tracker on task finished
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: 'OK'
        404:
          description: Job not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  parameters:
    taskId:
      in: path
      name: taskId
      description: ID of task
      required: true
      schema:
        $ref: '#/components/schemas/taskId'
  schemas:
    taskId:
      type: string
      format: uuid
    error:
      type: object
      properties:
        message:
          type: string
        stacktrace:
          type: string
      required:
        - message
