{{- $configmapName := include "configmap.fullname" . }}
{{- $jobManagement := (include "common.jobManagement.merged" .) | fromYaml }}
{{- $serviceUrls := (include "common.serviceUrls.merged" .) | fromYaml }}
{{- $queue := .Values.env.queue }}
{{- $tracing := (include "common.tracing.merged" .) | fromYaml }}
{{- $metrics := (include "common.metrics.merged" .) | fromYaml }}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if $tracing.enabled | quote}}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracing.url }}
  {{ end }}
  {{ if $metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metrics.url }}
  {{ end }}
  npm_config_cache: /tmp/
  JOB_MANAGER_BASE_URL: {{ $serviceUrls.jobManager | quote }}
  HEARTBEAT_BASE_URL: {{ $serviceUrls.heartbeatManager | quote }}
  HEARTBEAT_INTERVAL_MS: {{ $queue.heartbeatIntervalMs | quote }}
  JOB_MANAGER_DEQUEUE_INTERVAL_MS: {{ $queue.dequeueIntervalMs | quote }}
  TASK_TYPES_INIT: {{ $jobManagement.ingestion.init | quote }}
  TASK_TYPES_TILES_MERGING: -
  {{ ( $jobManagement.ingestion.new.mergeTilesTaskType | default $jobManagement.ingestion.update.mergeTilesTaskType) | quote }}
  TASK_TYPES_POLYGON_PARTS: {{ $jobManagement.ingestion.polygonParts.taskType | quote }}
  TASK_TYPES_FINALIZE: {{ $jobManagement.ingestion.finalize.taskType | quote }}
{{- end }}
